version: '3.3'

services:
  wakeup-coach:
    build: .
    container_name: wakeup-coach
    restart: unless-stopped
    ports:
      - "8765:8000"  # Using port 8765 externally, mapped to 8000 internally
    networks:
      - wakeup_network
    volumes:
      - ./config:/app/config
    env_file:
      - .env
    environment:
      - TZ=America/New_York  # Change this to your timezone
      - PORT=8000  # Internal port
      - EXTERNAL_PORT=8765  # External port for Twilio to use

networks:
  wakeup_network:
    driver: macvlan
    driver_opts:
      parent: eth0  # Change this to your network interface (e.g., eth0, ens33, etc.)
    ipam:
      config:
        - subnet: 192.168.0.0/24  # Change this to your network subnet
          gateway: 192.168.0.1     # Change this to your network gateway
          ip_range: 192.168.0.100/29  # Assign a specific IP range for the container 